esphome:
  name: "${name}"
  friendly_name: Apollo MSR-2
  comment: Apollo MSR-2
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.MSR-2"
    version: "${version}"

  min_version: 2024.6.4

logger:

packages:
  core: !include Core.yaml