substitutions:
  name: apollo-msr-2
  version:  "24.7.4.1"
  device_description: ${name} made by Apollo Automation - version ${version}.
  
esphome:
  name: "${name}"
  friendly_name: Apollo MSR-2
  comment: Apollo MSR-2
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
  - priority: 900.0
    then:
      - lambda: |-
          id(radar_bluetooth).turn_off();
  - priority: -10
    then:
      - if:
          condition:
            - lambda: "return id(runTest);"
          then:
            - lambda: "id(testScript).execute();"

  project:
    name: "ApolloAutomation.MSR-2"
    version: "${version}"

  min_version: 2024.6.0

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
  
dashboard_import:
  package_import_url: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2.yaml
  import_full_config: false

ota:
  - platform: esphome
    id: ota_default
  - platform: http_request
    id: ota_managed

http_request:
  useragent: esphome/device
  timeout: 10s
  verify_ssl: false

update:
  - platform: http_request
    id: firmware_update
    name: Firmware Update
    source: https://apolloautomation.github.io/MSR-2/artifact/manifest.json

safe_mode:

improv_serial:

esp32_improv:
  authorizer: none

wifi:
  ap:
    ssid: "Apollo MSR2 Hotspot"

captive_portal:

logger:
  level: WARN

packages:
  remote_package:
    url: https://github.com/ApolloAutomation/MSR-2/
    ref: main
    files:
      - Integrations/ESPHome/Core.yaml
    refresh: 0d