#Define Project
substitutions:
  name: apollo-msr-2
  version:  "24.7.4.1"
  device_description: ${name} made by Apollo Automation - version ${version}.
  
esphome:
  name: "${name}"
  friendly_name: Apollo MSR-2
  comment: Apollo MSR-2
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  on_boot:
  - priority: 900.0
    then:
      - lambda: |-
          id(radar_bluetooth).turn_off();
  - priority: -10
    then:
      - if:
          condition:
            - lambda: "return id(runTest);"
          then:
            - lambda: "id(testScript).execute();"

  project:
    name: "ApolloAutomation.MSR-2"
    version: "${version}"

  min_version: 2024.6.0

# Define Board
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
  
dashboard_import:
  package_import_url: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2.yaml
  import_full_config: false

packages:
  remote_package:
    url: https://github.com/ApolloAutomation/MSR-2/
    ref: SplitYaml
    files:
      - Integrations/ESPHome/Core.yaml
    refresh: 0d