name: Weekly Firmware Build

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - Integrations/ESPHome/MSR-2_Factory.yaml
          - Integrations/ESPHome/MSR-2.yaml
          - Integrations/ESPHome/MSR-2_BLE.yaml
        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5.0.0
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ matrix.file }}